In [1]:
!ls ../../Thymus_processed*

../../Thymus_processed.loom

In [2]:
from descartes_rpa.convert.loom import loom_to_anndata

In [6]:
adata = loom_to_anndata(
    file="../../Thymus_processed.loom"
)

In [7]:
adata.var_names

Index(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
       ...
       '63551', '63552', '63553', '63554', '63555', '63556', '63557', '63558',
       '63559', '63560'],
      dtype='object', length=63561)

In [8]:
adata.obs_names

Index(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
       ...
       '8769', '8770', '8771', '8772', '8773', '8774', '8775', '8776', '8777',
       '8778'],
      dtype='object', length=8779)

In [9]:
adata

AnnData object with n_obs × n_vars = 8779 × 63561
    obs: 'All_reads', 'Assay', 'Batch', 'Development_day', 'Exon_reads', 'Experiment_batch', 'Fetus_id', 'Intron_reads', 'Main_cluster_name', 'Main_cluster_umap_1', 'Main_cluster_umap_2', 'Organ', 'Organ_cell_lineage', 'RT_group', 'Sex', 'Size_Factor', 'n_counts', 'obs_names', 'sample'
    var: 'exon_intron', 'gene_id', 'gene_short_name', 'gene_type', 'index', 'var_names'

In [10]:
adata.var

,exon_intron,gene_id,gene_short_name,gene_type,index,var_names
0,exon,ENSG00000223972.4,DDX11L1,pseudogene,1,ENSG00000223972.4
1,exon,ENSG00000227232.4,WASH7P,pseudogene,3,ENSG00000227232.4
2,exon,ENSG00000243485.2,MIR1302-11,lincRNA,5,ENSG00000243485.2
3,exon,ENSG00000237613.2,FAM138A,lincRNA,7,ENSG00000237613.2
4,exon,ENSG00000268020.2,OR4G4P,pseudogene,9,ENSG00000268020.2
...,...,...,...,...,...,...
63556,exon,ENSG00000240779.1,CU463998.1,miRNA,127113,ENSG00000240779.1
63557,exon,ENSG00000244656.1,CU463998.3,miRNA,127115,ENSG00000244656.1
63558,exon,ENSG00000263760.1,CU463998.4,miRNA,127117,ENSG00000263760.1
63559,exon,ENSG00000222670.2,CU459211.1,miRNA,127119,ENSG00000222670.2
63560,exon,ENSG00000251180.2,CU459201.1,protein_coding,127121,ENSG00000251180.2

In [11]:
adata.obs

,All_reads,Assay,Batch,Development_day,Exon_reads,Experiment_batch,Fetus_id,Intron_reads,Main_cluster_name,Main_cluster_umap_1,Main_cluster_umap_2,Organ,Organ_cell_lineage,RT_group,Sex,Size_Factor,n_counts,obs_names,sample
0,688,Nuclei,7,115,128,exp4,H27423,467,Thymocytes,1.480319,1.717246,Thymus,Thymus-Thymocytes,Thymus_H27423,M,NaN,592.0,exp4-human-101well.ATGCTTCCTAACCATTGGA,exp4-human-101well.ATGCTTCCTAACCATTGGA
1,559,Nuclei,7,115,173,exp4,H27423,316,Thymocytes,1.836766,0.828598,Thymus,Thymus-Thymocytes,Thymus_H27423,M,NaN,487.0,exp4-human-103well.TTCCATTACTTTATTCATTC,exp4-human-103well.TTCCATTACTTTATTCATTC
2,312,Nuclei,7,115,222,exp4,H27423,39,Thymocytes,1.720090,1.417247,Thymus,Thymus-Thymocytes,Thymus_H27423,M,NaN,252.0,exp4-human-103well.GACCGTCATCATTCGACGG,exp4-human-103well.GACCGTCATCATTCGACGG
3,423,Nuclei,7,115,60,exp4,H27423,271,Thymocytes,1.329029,0.776162,Thymus,Thymus-Thymocytes,Thymus_H27423,M,NaN,330.0,exp4-human-104well.CCAGCCTTTTAACTGGTTA,exp4-human-104well.CCAGCCTTTTAACTGGTTA
4,341,Nuclei,7,115,140,exp4,H27423,165,Thymocytes,1.674138,1.022330,Thymus,Thymus-Thymocytes,Thymus_H27423,M,NaN,304.0,exp4-human-104well.CAAGCAACTTGGTCAGCCA,exp4-human-104well.CAAGCAACTTGGTCAGCCA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8774,429,Nuclei,4,110,174,exp3,H27471,176,Thymocytes,1.884309,1.473001,Thymus,Thymus-Thymocytes,Thymus_H27471,F,NaN,349.0,exp3-human-403well.AGAGTACCTTAGATCTACT,exp3-human-403well.AGAGTACCTTAGATCTACT
8775,342,Nuclei,4,110,97,exp3,H27471,199,Thymocytes,1.933699,0.883870,Thymus,Thymus-Thymocytes,Thymus_H27471,F,NaN,293.0,exp3-human-410well.ACAACCTATTCATCTCTGCA,exp3-human-410well.ACAACCTATTCATCTCTGCA
8776,311,Nuclei,4,110,130,exp3,H27471,137,Antigen presenting cells,1.491640,2.114090,Thymus,Thymus-Antigen presenting cells,Thymus_H27471,F,NaN,266.0,exp3-human-423well.TTCTCATTGTACTTAACCTT,exp3-human-423well.TTCTCATTGTACTTAACCTT
8777,389,Nuclei,4,110,104,exp3,H27471,231,Thymocytes,1.471399,1.168557,Thymus,Thymus-Thymocytes,Thymus_H27471,F,NaN,332.0,exp3-human-476well.TCCAAGTTATATCCATGACT,exp3-human-476well.TCCAAGTTATATCCATGACT
8778,733,Nuclei,4,110,201,exp3,H27471,420,Thymocytes,1.236487,1.379843,Thymus,Thymus-Thymocytes,Thymus_H27471,F,NaN,619.0,exp3-human-478well.GGTCAGTTTACCGCCAACC,exp3-human-478well.GGTCAGTTTACCGCCAACC